export const qk = {
  me: ["me"] as const,
  feed: (tab: string) => ["feed", tab] as const,
  post: (id: string) => ["post", id] as const,
  comments: (postId: string) => ["comments", postId] as const,
  profile: (username: string) => ["profile", username] as const,
  userPosts: (username: string) => ["user-posts", username] as const,
  anonPosts: ["anon-posts"] as const,
  bookmarks: ["bookmarks"] as const,
  circles: (q?: string, mine?: boolean) => ["circles", q ?? "", mine ?? false] as const,
  circle: (slug: string) => ["circle", slug] as const,
  circlePosts: (slug: string) => ["circle-posts", slug] as const,
  circleMembers: (slug: string) => ["circle-members", slug] as const,
  tagPosts: (tag: string) => ["tag-posts", tag] as const,
  trending: ["trending"] as const,
  tags: ["tags"] as const,
  pulse: ["pulse"] as const,
  people: ["people"] as const,
  suggestedCircles: ["suggested-circles"] as const,
  search: (q: string, type: string) => ["search", type, q] as const,
  conversations: (filter: string) => ["conversations", filter] as const,
  conversation: (id: string) => ["conversation", id] as const,
  messages: (id: string) => ["messages", id] as const,
  dmUnread: ["dm-unread"] as const,
  notifications: ["notifications"] as const,
  unread: ["unread"] as const,
  moodSummary: ["mood-summary"] as const,
  moodHistory: (days: number) => ["mood-history", days] as const,
  companionSessions: ["companion-sessions"] as const,
  companionSession: (id: string) => ["companion-session", id] as const,
  reframes: ["reframes"] as const,
  reflection: ["reflection"] as const,
  aiStatus: ["ai-status"] as const,
  billing: ["billing"] as const,
  sessions: ["sessions"] as const,
  blocked: ["blocked"] as const,
  modReports: (status: string) => ["mod-reports", status] as const,
  modStats: ["mod-stats"] as const,
};
